INSERT INTO USER (USER_ID, EMAIL, PASSWORD, ACTIVATED)
VALUES (1, 'admin@gmail.com', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');

INSERT INTO PRODUCT (PRD_ID, PRD_NM, PRICE) VALUES (1,'사과',5000);
INSERT INTO PRODUCT (PRD_ID, PRD_NM, PRICE) VALUES (2,'바나나',3000);
INSERT INTO PRODUCT (PRD_ID, PRD_NM, PRICE) VALUES (3,'딸기',7000);
INSERT INTO PRODUCT (PRD_ID, PRD_NM, PRICE) VALUES (4,'토마토',4000);
INSERT INTO PRODUCT (PRD_ID, PRD_NM, PRICE) VALUES (5,'수박',10000);

INSERT INTO ORDER_TABLE (ORD_ID, USER_ID, PRD_ID) VALUES (1,1,1);
INSERT INTO ORDER_TABLE (ORD_ID, USER_ID, PRD_ID) VALUES (2,1,2);
